apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - sockshop-staging-gateway.sockshop-staging
  - mesh
  hosts:
  - carts-db.sockshop-staging.35.197.167.182.xip.io
  - carts-db
  - carts-db.sockshop-staging
  http:
  - route:
    - destination:
        host: carts-db.sockshop-staging.svc.cluster.local
